export const regExConstant ={
    "email": (/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/),
    "onlyNumber": (/^[0-9]*$/),
    "mobileNumber": (/^[0][6-9]\d{9}$|^[6-9]\d{9}$/),
    "gstNumber": (/\d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}/),
    "onlyTwoDecimals": (/^[0-9]+(\.[0-9]{1,2})?$/),
    "onlyAlphaNumeric": (/^[a-zA-Z0-9]*$/),
    "panNumber": (/^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}?$/),
    "uidNumber": (/^([0-9]){12}?$/),
    "passportNumber": (/^(?!^0+$)[a-zA-Z0-9]{3,20}$/),
    "dlNumber": (/^[a-zA-Z0-9-_ ]*$/),
    "voterNumber": (/^[a-zA-Z0-9-_ ]*$/),
    "defaultCharacter": (/^[a-zA-Z0-9_@!#$%&*+-/, ]*$/),
    "sanctionConditionSpecialChar": (/^[^*|\":<>[\]{}`\\';@&$!~#^?/=_]+$/),
    "restrictedSpecialCharacter": (/^[^*|\":<>[\]{}`\\';@&$!~#^?/=_]+$/),
    "stringsAlphaNumeric": (/^[a-zA-Z0-9-_ ]*$/),
    "alphabetsOnly": (/^[a-zA-Z-_ ]*$/),
    "floatNumberOnly": (/^[.0-9]*$/),
    "defaultNumbers": (/^[0-9_.,% ]*$/),
    "rupees": (/^([₹])?[0-9\,]+(\.[0-9]+)?$/),
    "password":(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/),
    "latitude": (/^(\+|-)?((\d((\.)|\.\d{1,6})?)|(0*?[0-8]\d((\.)|\.\d{1,6})?)|(0*?90((\.)|\.0{1,6})?))$/),
    "longitude": (/^(\+|-)?((\d((\.)|\.\d{1,6})?)|(0*?\d\d((\.)|\.\d{1,6})?)|(0*?1[0-7]\d((\.)|\.\d{1,6})?)|(0*?180((\.)|\.0{1,6})?))$/),
    "signedNumbers": (/^[0-9-.]*$/),
    "negativeNumbers": (/^\-?(\d+\.?\d*|\d*\.?\d+)$/),
}


